# .travis.yml
language: node_js
git:
  depth: 1
matrix:
  include:
  - node_js: '6.3'
    script: npm run travis
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
notifications:
  email: false
deploy:
  provider: npm
  email: $(node -p "JSON.parse(require('fs').readFileSync('./package.json').toString()).contributors[0]")
  on:
    branch: master
    tags: true