# .travis.yml
language: node_js
git:
  depth: 1
matrix:
  include:
  - node_js: '6.3'
    script: echo "hello"
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - echo "{\"email\":\"jim@vigour.io\",\"token\":\"${NOW_TOKEN}\"}" > .now.json
notifications:
  email: false
deploy:
  provider: script
  script: echo $(npm run deploy)
  on:
    branch: develop